package:
  name: biometalib
  version: 0.0.3
source:
  git_url: https://github.com/jfear/biometalib.git
  git_rev: master

build:
  number: {{ BIOMETALIB_BUILD }}

requirements:
  build:
    - bumpversion ==0.5.3
    - fuzzywuzzy >=0.15.0
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - pyyaml >=3.12
    - ruamel.yaml <0.15
    - sramongo >=0.0.1

  run:
    - bumpversion ==0.5.3
    - fuzzywuzzy >=0.15.0
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - pyyaml >=3.12
    - ruamel.yaml <0.15
    - sramongo >=0.0.1

test:
  imports:
    - biometalib

about:
  home: https://github.com/jfear/biometalib
  license: MIT
