package:
  name: biometalib
  version: 0.0.5
source:
  git_url: https://github.com/jfear/biometalib.git
  git_rev: master

build:
  number: {{ BIOMETALIB_BUILD }}

requirements:
  build:
    - python
    - fuzzywuzzy ==0.15.0
    - mongoengine >=0.11.0
    - numpy <=1.13.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - pyyaml >=3.12
    - ruamel.yaml <0.15.0
    - sramongo >=0.0.3
    - pluggy

  run:
    - python
    - fuzzywuzzy ==0.15.0
    - mongoengine >=0.11.0
    - numpy <=1.13.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - pyyaml >=3.12
    - ruamel.yaml <0.15.0
    - sramongo >=0.0.3
    - pluggy

test:
  imports:
    - biometalib

about:
  home: https://github.com/jfear/biometalib
  license: MIT
